Supplier update
websolcr/com-proj-pos-nethsara pull request #81
Opened 2022-01-02 18:38 UTC by Kushan1994

2022-01-03 03:55 UTC, sureshhemal requested changes

2022-01-03 03:55 UTC, sureshhemal commented on app/Actions/GenarateBarcode.php
> +<?php
Delete this file. `GenarateBarcode.php`

2022-01-03 03:55 UTC, sureshhemal commented on resources/js/Components/Supplier/Form.vue
>      <FormGruop>
Replace `FormGruop` with correct spellings

2022-01-03 03:55 UTC, sureshhemal commented on resources/js/Components/Supplier/Form.vue
>      </FormGruop>
where is the `textarea` field

2022-01-03 03:55 UTC, sureshhemal commented on resources/js/Components/Supplier/Form.vue
> +const editableUUID = computed(() => {
add a space line between two separate sections

2022-01-03 03:55 UTC, sureshhemal commented on resources/js/Pages/Supplier/Index.vue
> +            <InertiaLink :href="route('suppliers.create')">
remove `:href=...` and make `@click=create` and `function create()`

2022-01-03 03:55 UTC, sureshhemal commented on resources/js/Pages/Supplier/Update.vue
> +let props = defineProps({
add a space line

2022-01-04 17:19 UTC, Kushan1994 commented on resources/js/Pages/Supplier/Index.vue
> +            <InertiaLink :href="route('suppliers.create')">
later

2022-01-04 17:41 UTC, sureshhemal approved these changes

2022-01-04 17:54 UTC, merged